services:
  - type: web
    name: portfolio
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 