services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm ci && NODE_ENV=production npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 