services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install && ./node_modules/.bin/vite build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 